<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\System.Data.Async.DataSet\System.Data.Async.DataSet.csproj" />
    <ProjectReference Include="..\..\src\System.Data.Async.DataSet.Generator\System.Data.Async.DataSet.Generator.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false" />
    <ProjectReference Include="..\..\src\System.Data.Async.Serialization.NewtonsoftJson\System.Data.Async.Serialization.NewtonsoftJson.csproj" />
    <ProjectReference Include="..\..\src\System.Data.Async.Serialization.SystemTextJson\System.Data.Async.Serialization.SystemTextJson.csproj" />
  </ItemGroup>

  <ItemGroup>
    <AdditionalFiles Include="Schemas\*.xsd" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.1*" />
    <PackageReference Include="xunit" Version="2.*" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.*" />
    <PackageReference Include="FluentAssertions" Version="8.1*" />
  </ItemGroup>
</Project>
